language: go
go:
  - "1.7.x"

go_import_path: hitman

before_install:
  - nvm install 6
  - npm i -g yarn --cache-min 9999999

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.yarn-cache
    - $HOME/.npm

install:
  - yarn --pure-lockfile
  - yarn global add codecov
  - go get -u github.com/modocache/gover
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/Masterminds/glide
  - glide install

script:
  - go list -f '"go test -v -covermode=atomic -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"' ./pkg/... | xargs -I % sh -c %
  - gover ./ ./coverage.txt
  - ./node_modules/.bin/jest --coverage

after_success:
  - cat ./coverage.txt
  - bash <(curl -s https://codecov.io/bash) -f ./coverage.txt
  - codecov
